baseurl = "http://www.luanova.org"
languageCode = "en-us"
title = "lua nova"

[permalinks]
post = "/:filename/"
about = "/:filename/"

[Params]
Subtitle = "welcome to the moon"
GaugesId = "505378cd613f5d0d9d000047"
